# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lab8001.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(629, 459)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Initials = QtWidgets.QLabel(self.centralwidget)
        self.label_Initials.setGeometry(QtCore.QRect(30, 30, 221, 101))
        self.label_Initials.setObjectName("label_Initials")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 150, 71, 31))
        self.label.setObjectName("label")
        self.label_Result = QtWidgets.QLabel(self.centralwidget)
        self.label_Result.setGeometry(QtCore.QRect(100, 160, 60, 16))
        self.label_Result.setObjectName("label_Result")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 210, 141, 16))
        self.label_6.setObjectName("label_6")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(30, 230, 151, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(210, 230, 151, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.labe_InputMessage = QtWidgets.QLabel(self.centralwidget)
        self.labe_InputMessage.setEnabled(True)
        self.labe_InputMessage.setGeometry(QtCore.QRect(200, 370, 201, 16))
        self.labe_InputMessage.setObjectName("labe_InputMessage")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(400, 10, 201, 321))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(5)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 181, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(80, 40, 21, 21))
        self.label_3.setObjectName("label_3")
        self.horizontalSlider = QtWidgets.QSlider(self.frame)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 60, 160, 22))
        self.horizontalSlider.setMaximum(20)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_AOut = QtWidgets.QLabel(self.frame)
        self.label_AOut.setGeometry(QtCore.QRect(60, 90, 60, 16))
        self.label_AOut.setObjectName("label_AOut")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(80, 120, 21, 21))
        self.label_4.setObjectName("label_4")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(10, 150, 160, 22))
        self.horizontalSlider_2.setMaximum(20)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label_BOut = QtWidgets.QLabel(self.frame)
        self.label_BOut.setGeometry(QtCore.QRect(60, 180, 60, 16))
        self.label_BOut.setObjectName("label_BOut")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(80, 210, 21, 21))
        self.label_5.setObjectName("label_5")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(10, 240, 160, 22))
        self.horizontalSlider_3.setMaximum(20)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.label_COut = QtWidgets.QLabel(self.frame)
        self.label_COut.setGeometry(QtCore.QRect(60, 270, 60, 16))
        self.label_COut.setObjectName("label_COut")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(200, 260, 161, 101))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit_A = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_A.setGeometry(QtCore.QRect(40, 10, 113, 21))
        self.lineEdit_A.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_A.setInputMask("")
        self.lineEdit_A.setObjectName("lineEdit_A")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 21, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 21, 21))
        self.label_8.setObjectName("label_8")
        self.lineEdit_B = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_B.setGeometry(QtCore.QRect(40, 40, 113, 21))
        self.lineEdit_B.setObjectName("lineEdit_B")
        self.lineEdit_C = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_C.setGeometry(QtCore.QRect(40, 70, 113, 21))
        self.lineEdit_C.setObjectName("lineEdit_C")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(10, 70, 21, 21))
        self.label_9.setObjectName("label_9")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(30, 260, 141, 121))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.spinBox = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox.setGeometry(QtCore.QRect(10, 40, 48, 24))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_2.setGeometry(QtCore.QRect(10, 90, 48, 24))
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 60, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(10, 0, 121, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(10, 70, 60, 16))
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 629, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lab8_Sherstiuk"))
        self.label_Initials.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Шерстюк Ігор Юрійович</span></p><p><span style=\" font-size:18pt;\">Група: ІВ-92</span></p><p><span style=\" font-size:18pt;\">Номер: 9231</span></p><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Результат:"))
        self.label_Result.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "Елементи множин"))
        self.radioButton.setText(_translate("MainWindow", "Задання випадково"))
        self.radioButton_2.setText(_translate("MainWindow", "Задання вручну"))
        self.labe_InputMessage.setText(_translate("MainWindow", "Напишіть цифри через кому"))
        self.label_2.setText(_translate("MainWindow", "Кількість єлементів A,B,C"))
        self.label_3.setText(_translate("MainWindow", "A"))
        self.label_AOut.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "B"))
        self.label_BOut.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "C"))
        self.label_COut.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "A"))
        self.label_8.setText(_translate("MainWindow", "B"))
        self.label_9.setText(_translate("MainWindow", "C"))
        self.label_10.setText(_translate("MainWindow", "Початок"))
        self.label_11.setText(_translate("MainWindow", "Визначте діапазон"))
        self.label_12.setText(_translate("MainWindow", "Кінець"))
